version: "3.9"
services:
  concert_application:
    image: fhi-git.fraunhofer.it:5050/concert/concert_application:devel
    container_name: concert_application
    build:
      context: ..
      dockerfile: docker/Dockerfile
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY}
      - CYCLONEDDS_URI=${CYCLONEDDS_URI}
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    privileged: true
    volumes:
      - ../:/concert_application_ws/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw